const API='https://tglsxxbgcmozqcgytwch.supabase.co/functions/v1/vinnu-admin-api';
const events=[
  ['🎂','Birthday Parties','birthday','Theme birthdays, balloon styling, cake areas, welcome boards and custom celebration setups.'],
  ['👶','Baby & Naming','baby','Baby shower, naming ceremony, cradle ceremony, welcome baby and family celebration decor.'],
  ['💗','Surprises','surprises','Birthday surprises, anniversaries, proposals, room setups and special reaction moments.'],
  ['🪔','Haldi & Mehendi','haldi-mehendi','Traditional and modern haldi and mehendi stages, floral styling, seating and photo areas.'],
  ['💍','Engagements','engagements','Ring ceremony stages, entrances, floral backdrops, welcome boards and couple-focused styling.'],
  ['👰','Weddings','weddings','Wedding and reception decor, venue planning, stage, entrance and custom concepts.'],
  ['💼','Corporate Events','corporate','Business openings, annual days, conferences, award functions, launches and employee events.'],
  ['✨','More Events','more','Housewarmings, school and college functions, cultural programs and custom celebrations.']
];
let mediaItems=[],loaded=false,storyAudio=null,storyProgressTimer=null;
const $=id=>document.getElementById(id);
const THEME_KEY='vinnu_theme';
function activeTheme(){return document.documentElement.getAttribute('data-theme')==='dark'?'dark':'light'}
function applyTheme(theme,persist=true){const next=theme==='dark'?'dark':'light';document.documentElement.setAttribute('data-theme',next);if(persist){try{localStorage.setItem(THEME_KEY,next)}catch(e){}}const b=$('themeToggle');if(b){const target=next==='dark'?'light':'dark';b.setAttribute('aria-label',`Switch to ${target} mode`);b.title=`Switch to ${target} mode`}const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.setAttribute('content',next==='dark'?'#13080e':'#6f1233')}
const themeToggle=$('themeToggle');if(themeToggle){applyTheme(activeTheme(),false);themeToggle.onclick=()=>applyTheme(activeTheme()==='dark'?'light':'dark',true)}
try{const mq=window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)');if(mq&&mq.addEventListener)mq.addEventListener('change',e=>{if(!localStorage.getItem(THEME_KEY))applyTheme(e.matches?'dark':'light',false)})}catch(e){}
function youtubeId(raw=''){const s=String(raw);const direct=s.match(/^[A-Za-z0-9_-]{11}$/)?.[0];if(direct)return direct;try{const u=new URL(s),h=u.hostname.replace(/^www\./,'').toLowerCase();let id='';if(h==='youtu.be')id=u.pathname.split('/').filter(Boolean)[0]||'';else if(h.endsWith('youtube.com')||h.endsWith('youtube-nocookie.com')){if(u.pathname==='/watch')id=u.searchParams.get('v')||'';else{const p=u.pathname.split('/').filter(Boolean);if(['shorts','embed','live'].includes(p[0]||''))id=p[1]||''}}return /^[A-Za-z0-9_-]{11}$/.test(id)?id:''}catch{return ''}}
async function loadMedia(force=false){if(loaded&&!force)return;try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'list'})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load media');mediaItems=d.items||[]}catch(e){console.warn(e);mediaItems=[]}finally{loaded=true;renderDemos()}}
function demoMeta(item,card){const meta=document.createElement('div');meta.className='demo-meta';const b=document.createElement('b');b.textContent=item.title||'Vinnu Events Demo';const p=document.createElement('p');p.textContent=item.caption||'Event highlight';meta.append(b,p);card.appendChild(meta)}
function makeDemo(item){const card=document.createElement('article');card.className='demo-card reveal';if(item.media_type==='youtube'){const id=youtubeId(item.public_url)||String(item.storage_path||'').replace(/^youtube:/,'');const iframe=document.createElement('iframe');iframe.src=`https://www.youtube-nocookie.com/embed/${id}?rel=0&playsinline=1`;iframe.title=item.title||'Vinnu Events Demo';iframe.loading='lazy';iframe.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share';iframe.allowFullscreen=true;card.classList.add('youtube-demo');card.appendChild(iframe)}else{const v=document.createElement('video');v.src=item.public_url;v.controls=true;v.preload='metadata';v.playsInline=true;v.setAttribute('controlsList','nodownload');v.addEventListener('loadedmetadata',()=>{if(v.videoWidth&&v.videoHeight)card.style.setProperty('--video-ratio',`${v.videoWidth}/${v.videoHeight}`)});card.appendChild(v)}demoMeta(item,card);observeReveal(card);return card}
function renderDemos(){const t=$('demoTrack');const demos=mediaItems.filter(x=>x.category==='demo-highlights'&&['video','youtube'].includes(x.media_type));t.innerHTML='';if(!demos.length){const e=document.createElement('div');e.className='demo-empty reveal';e.innerHTML='<div><b>Demo Highlights</b><span>Add a YouTube video link from Admin and it will appear here automatically.</span></div>';t.appendChild(e);observeReveal(e);updateDemoNav();return}demos.forEach(x=>t.appendChild(makeDemo(x)));requestAnimationFrame(updateDemoNav)}
function demoStep(){const t=$('demoTrack');const cards=[...t.querySelectorAll('.demo-card')];if(cards.length>1){const a=cards[0].getBoundingClientRect(),b=cards[1].getBoundingClientRect();return Math.max(1,Math.round(b.left-a.left))}const c=cards[0];return c?c.getBoundingClientRect().width+20:Math.max(300,t.clientWidth*.8)}
function scrollDemo(dir){const t=$('demoTrack');t.scrollBy({left:demoStep()*dir,behavior:'smooth'});setTimeout(updateDemoNav,350)}
function updateDemoNav(){const t=$('demoTrack'),prev=$('demoPrev'),next=$('demoNext');if(!t||!prev||!next)return;const max=Math.max(0,t.scrollWidth-t.clientWidth),eps=8;prev.disabled=t.scrollLeft<=eps;next.disabled=t.scrollLeft>=max-eps;prev.style.opacity=prev.disabled?'.4':'1';next.style.opacity=next.disabled?'.4':'1';prev.style.cursor=prev.disabled?'default':'pointer';next.style.cursor=next.disabled?'default':'pointer'}
$('demoPrev').onclick=()=>{if(!$('demoPrev').disabled)scrollDemo(-1)};$('demoNext').onclick=()=>{if(!$('demoNext').disabled)scrollDemo(1)};$('demoTrack').addEventListener('scroll',()=>requestAnimationFrame(updateDemoNav),{passive:true});window.addEventListener('resize',updateDemoNav);

function ensureStoryViewer(){let viewer=$('storyViewer');if(viewer)return viewer;viewer=document.createElement('div');viewer.id='storyViewer';viewer.className='story-viewer';viewer.setAttribute('role','dialog');viewer.setAttribute('aria-modal','true');viewer.setAttribute('aria-label','Vinnu Events photo story');viewer.innerHTML=`<div class="story-frame"><div class="story-progress"><span id="storyProgressBar"></span></div><div class="story-top"><div class="story-brand"><span class="story-brand-dot"></span><div><b>Vinnu Events</b><small>Celebrate Every Moment</small></div></div><button class="story-music hidden" id="storyMusic" type="button" aria-label="Play or pause music">♫ <span id="storyMusicText">Music</span></button><button class="story-close" id="storyClose" type="button" aria-label="Close story">×</button></div><img id="storyImage" alt="Vinnu Events event photo"><div class="story-shade"></div><div class="story-copy"><div class="story-music-line hidden" id="storyMusicLine">♫ <span id="storySongTitle"></span></div><h3 id="storyTitle"></h3><p id="storyCaption"></p><small class="story-hint">Tap the music button to pause or play</small></div><audio id="storyAudio" preload="metadata" playsinline></audio></div>`;document.body.appendChild(viewer);storyAudio=$('storyAudio');$('storyClose').onclick=closeStory;viewer.addEventListener('click',e=>{if(e.target===viewer)closeStory()});$('storyMusic').onclick=toggleStoryMusic;storyAudio.addEventListener('timeupdate',updateStoryProgress);storyAudio.addEventListener('loadedmetadata',updateStoryProgress);storyAudio.addEventListener('ended',()=>{storyAudio.currentTime=0;storyAudio.play().catch(()=>{})});return viewer}
function updateStoryProgress(){const bar=$('storyProgressBar');if(!bar||!storyAudio)return;const d=Number(storyAudio.duration)||0,c=Number(storyAudio.currentTime)||0;bar.style.width=d?`${Math.min(100,(c/d)*100)}%`:'0%'}
function setStoryMusicState(playing){const btn=$('storyMusic');if(!btn)return;btn.classList.toggle('playing',playing);btn.setAttribute('aria-label',playing?'Pause music':'Play music');btn.firstChild.nodeValue=playing?'❚❚ ':'♫ '}
async function toggleStoryMusic(){if(!storyAudio||!storyAudio.src)return;if(storyAudio.paused){try{await storyAudio.play();setStoryMusicState(true)}catch(e){setStoryMusicState(false)}}else{storyAudio.pause();setStoryMusicState(false)}}
async function openStory(item){const viewer=ensureStoryViewer(),img=$('storyImage');img.src=item.public_url;img.alt=item.title||'Vinnu Events event photo';$('storyTitle').textContent=item.title||'Vinnu Events';$('storyCaption').textContent=item.caption||'';const hasMusic=Boolean(item.music_url);$('storyMusic').classList.toggle('hidden',!hasMusic);$('storyMusicLine').classList.toggle('hidden',!hasMusic);$('storySongTitle').textContent=item.music_title||'Music';$('storyMusicText').textContent=item.music_title||'Music';$('storyProgressBar').style.width='0%';viewer.classList.add('open');document.body.classList.add('story-open');if(storyAudio){storyAudio.pause();storyAudio.currentTime=0;storyAudio.src=hasMusic?item.music_url:'';setStoryMusicState(false);if(hasMusic){try{await storyAudio.play();setStoryMusicState(true)}catch(e){setStoryMusicState(false)}}}}
function closeStory(){const viewer=$('storyViewer');if(viewer)viewer.classList.remove('open');document.body.classList.remove('story-open');if(storyAudio){storyAudio.pause();storyAudio.currentTime=0;setStoryMusicState(false)}}

function mediaCard(x){const c=document.createElement('div');c.className='media reveal';let el;if(x.media_type==='youtube'){const id=youtubeId(x.public_url)||String(x.storage_path||'').replace(/^youtube:/,'');el=document.createElement('iframe');el.src=`https://www.youtube-nocookie.com/embed/${id}?rel=0&playsinline=1`;el.title=x.title||'Vinnu Events video';el.loading='lazy';el.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share';el.allowFullscreen=true}else if(x.media_type==='video'){el=document.createElement('video');el.src=x.public_url;el.controls=true;el.preload='metadata';el.playsInline=true}else{c.classList.add('media-image');c.tabIndex=0;c.setAttribute('role','button');c.setAttribute('aria-label',`Open ${x.title||'event photo'} story`);el=document.createElement('img');el.src=x.public_url;el.alt=x.title||'Vinnu Events event photo';el.loading='lazy';c.onclick=()=>openStory(x);c.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openStory(x)}};if(x.music_url){const badge=document.createElement('span');badge.className='music-badge';badge.textContent=`♫ ${x.music_title||'Music'}`;c.appendChild(badge)}}c.appendChild(el);const cap=document.createElement('div');cap.className='media-cap';const b=document.createElement('b');b.textContent=x.title||'Vinnu Events';const s=document.createElement('span');s.textContent=x.caption||'';cap.append(b,s);if(x.music_url&&x.media_type==='image'){const m=document.createElement('small');m.className='media-song';m.textContent=`♫ ${x.music_title||'Music'}`;cap.appendChild(m)}c.appendChild(cap);observeReveal(c);return c}
async function openCategory(ev){$('modalTitle').textContent=ev[1];$('modalText').textContent=ev[3];$('gallery').innerHTML='';$('galleryEmpty').style.display='block';$('galleryEmpty').textContent='Loading media…';$('modal').classList.add('open');await loadMedia();const items=mediaItems.filter(x=>x.category===ev[2]);$('galleryEmpty').style.display=items.length?'none':'block';if(!items.length)$('galleryEmpty').textContent='Photos and videos for this category will appear here when published from Admin.';items.forEach(x=>$('gallery').appendChild(mediaCard(x)))}

let revealObserver=null;
function getRevealObserver(){if(revealObserver)return revealObserver;if(!('IntersectionObserver'in window))return null;revealObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');revealObserver.unobserve(entry.target)}})},{threshold:.12,rootMargin:'0px 0px -6% 0px'});return revealObserver}
function observeReveal(el){el.classList.add('reveal');const o=getRevealObserver();if(o)o.observe(el);else el.classList.add('in-view')}
function setupReveals(){document.querySelectorAll('.section-title,.trust>div,.contact-wrap,.footer-inner,.hero-head,.logo-center').forEach(observeReveal)}

const grid=$('eventGrid');events.forEach((ev,i)=>{const c=document.createElement('article');c.className='event-card';c.style.setProperty('--reveal-delay',`${Math.min(i,7)*55}ms`);c.tabIndex=0;c.setAttribute('role','button');c.setAttribute('aria-label',`View ${ev[1]} gallery`);c.innerHTML=`<div class="event-icon">${ev[0]}</div><h3>${ev[1]}</h3><span>View gallery →</span>`;c.onclick=()=>openCategory(ev);c.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openCategory(ev)}};grid.appendChild(c);observeReveal(c)});
$('close').onclick=()=>$('modal').classList.remove('open');$('modal').onclick=e=>{if(e.target===$('modal'))$('modal').classList.remove('open')};document.addEventListener('keydown',e=>{if(e.key==='Escape'){if($('storyViewer')?.classList.contains('open'))closeStory();else $('modal').classList.remove('open')}});
setupReveals();loadMedia();setInterval(()=>loadMedia(true),90000);
