const API='https://tglsxxbgcmozqcgytwch.supabase.co/functions/v1/vinnu-admin-api';
const events=[
  ['🎂','Birthday Parties','birthday','Theme birthdays, balloon styling, cake areas, welcome boards and custom celebration setups.'],
  ['👶','Baby & Naming','baby','Baby shower, naming ceremony, cradle ceremony, welcome baby and family celebration decor.'],
  ['💗','Surprises','surprises','Birthday surprises, anniversaries, proposals, room setups and special reaction moments.'],
  ['🪔','Haldi & Mehendi','haldi-mehendi','Traditional and modern haldi and mehendi stages, floral styling, seating and photo areas.'],
  ['💍','Engagements','engagements','Ring ceremony stages, entrances, floral backdrops, welcome boards and couple-focused styling.'],
  ['👰','Weddings','weddings','Wedding and reception decor, venue planning, stage, entrance and custom concepts.'],
  ['💼','Corporate Events','corporate','Business openings, annual days, conferences, award functions, launches and employee events.'],
  ['✨','More Events','more','Housewarmings, school and college functions, cultural programs and custom celebrations.']
];
let mediaItems=[],loaded=false;
const $=id=>document.getElementById(id);
const THEME_KEY='vinnu_theme';
function activeTheme(){return document.documentElement.getAttribute('data-theme')==='dark'?'dark':'light'}
function applyTheme(theme,persist=true){const next=theme==='dark'?'dark':'light';document.documentElement.setAttribute('data-theme',next);if(persist){try{localStorage.setItem(THEME_KEY,next)}catch(e){}}const b=$('themeToggle');if(b){const target=next==='dark'?'light':'dark';b.setAttribute('aria-label',`Switch to ${target} mode`);b.title=`Switch to ${target} mode`}const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.setAttribute('content',next==='dark'?'#13080e':'#6f1233')}
const themeToggle=$('themeToggle');if(themeToggle){applyTheme(activeTheme(),false);themeToggle.onclick=()=>applyTheme(activeTheme()==='dark'?'light':'dark',true)}
try{const mq=window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)');if(mq&&mq.addEventListener)mq.addEventListener('change',e=>{if(!localStorage.getItem(THEME_KEY))applyTheme(e.matches?'dark':'light',false)})}catch(e){}
function youtubeId(raw=''){const s=String(raw);const direct=s.match(/^[A-Za-z0-9_-]{11}$/)?.[0];if(direct)return direct;try{const u=new URL(s),h=u.hostname.replace(/^www\./,'').toLowerCase();let id='';if(h==='youtu.be')id=u.pathname.split('/').filter(Boolean)[0]||'';else if(h.endsWith('youtube.com')||h.endsWith('youtube-nocookie.com')){if(u.pathname==='/watch')id=u.searchParams.get('v')||'';else{const p=u.pathname.split('/').filter(Boolean);if(['shorts','embed','live'].includes(p[0]||''))id=p[1]||''}}return /^[A-Za-z0-9_-]{11}$/.test(id)?id:''}catch{return ''}}
async function loadMedia(force=false){if(loaded&&!force)return;try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'list'})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load media');mediaItems=d.items||[]}catch(e){console.warn(e);mediaItems=[]}finally{loaded=true;renderDemos()}}
function demoMeta(item,card){const meta=document.createElement('div');meta.className='demo-meta';const b=document.createElement('b');b.textContent=item.title||'Vinnu Events Demo';const p=document.createElement('p');p.textContent=item.caption||'Event highlight';meta.append(b,p);card.appendChild(meta)}
function makeDemo(item){const card=document.createElement('article');card.className='demo-card';if(item.media_type==='youtube'){const id=youtubeId(item.public_url)||String(item.storage_path||'').replace(/^youtube:/,'');const iframe=document.createElement('iframe');iframe.src=`https://www.youtube-nocookie.com/embed/${id}?rel=0&playsinline=1`;iframe.title=item.title||'Vinnu Events Demo';iframe.loading='lazy';iframe.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share';iframe.allowFullscreen=true;card.classList.add('youtube-demo');card.appendChild(iframe)}else{const v=document.createElement('video');v.src=item.public_url;v.controls=true;v.preload='metadata';v.playsInline=true;v.setAttribute('controlsList','nodownload');v.addEventListener('loadedmetadata',()=>{if(v.videoWidth&&v.videoHeight)card.style.setProperty('--video-ratio',`${v.videoWidth}/${v.videoHeight}`)});card.appendChild(v)}demoMeta(item,card);return card}
function renderDemos(){const t=$('demoTrack');const demos=mediaItems.filter(x=>x.category==='demo-highlights'&&['video','youtube'].includes(x.media_type));t.innerHTML='';if(!demos.length){const e=document.createElement('div');e.className='demo-empty';e.innerHTML='<div><b>Demo Highlights</b><span>Add a YouTube video link from Admin and it will appear here automatically.</span></div>';t.appendChild(e);updateDemoNav();return}demos.forEach(x=>t.appendChild(makeDemo(x)));requestAnimationFrame(updateDemoNav)}
function demoStep(){const t=$('demoTrack');const cards=[...t.querySelectorAll('.demo-card')];if(cards.length>1){const a=cards[0].getBoundingClientRect(),b=cards[1].getBoundingClientRect();return Math.max(1,Math.round(b.left-a.left))}const c=cards[0];return c?c.getBoundingClientRect().width+20:Math.max(300,t.clientWidth*.8)}
function scrollDemo(dir){const t=$('demoTrack');t.scrollBy({left:demoStep()*dir,behavior:'smooth'});setTimeout(updateDemoNav,350)}
function updateDemoNav(){const t=$('demoTrack'),prev=$('demoPrev'),next=$('demoNext');if(!t||!prev||!next)return;const max=Math.max(0,t.scrollWidth-t.clientWidth),eps=8;prev.disabled=t.scrollLeft<=eps;next.disabled=t.scrollLeft>=max-eps;prev.style.opacity=prev.disabled?'.4':'1';next.style.opacity=next.disabled?'.4':'1';prev.style.cursor=prev.disabled?'default':'pointer';next.style.cursor=next.disabled?'default':'pointer'}
$('demoPrev').onclick=()=>{if(!$('demoPrev').disabled)scrollDemo(-1)};$('demoNext').onclick=()=>{if(!$('demoNext').disabled)scrollDemo(1)};$('demoTrack').addEventListener('scroll',()=>requestAnimationFrame(updateDemoNav),{passive:true});window.addEventListener('resize',updateDemoNav);
function mediaCard(x){const c=document.createElement('div');c.className='media';let el;if(x.media_type==='youtube'){const id=youtubeId(x.public_url)||String(x.storage_path||'').replace(/^youtube:/,'');el=document.createElement('iframe');el.src=`https://www.youtube-nocookie.com/embed/${id}?rel=0&playsinline=1`;el.title=x.title||'Vinnu Events video';el.loading='lazy';el.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share';el.allowFullscreen=true}else if(x.media_type==='video'){el=document.createElement('video');el.src=x.public_url;el.controls=true;el.preload='metadata';el.playsInline=true}else{el=document.createElement('img');el.src=x.public_url;el.alt=x.title||'Vinnu Events event photo';el.loading='lazy'}c.appendChild(el);const cap=document.createElement('div');cap.className='media-cap';const b=document.createElement('b');b.textContent=x.title||'Vinnu Events';const s=document.createElement('span');s.textContent=x.caption||'';cap.append(b,s);c.appendChild(cap);return c}
async function openCategory(ev){$('modalTitle').textContent=ev[1];$('modalText').textContent=ev[3];$('gallery').innerHTML='';$('galleryEmpty').style.display='block';$('galleryEmpty').textContent='Loading media…';$('modal').classList.add('open');await loadMedia();const items=mediaItems.filter(x=>x.category===ev[2]);$('galleryEmpty').style.display=items.length?'none':'block';if(!items.length)$('galleryEmpty').textContent='Photos and videos for this category will appear here when published from Admin.';items.forEach(x=>$('gallery').appendChild(mediaCard(x)))}
const grid=$('eventGrid');events.forEach(ev=>{const c=document.createElement('article');c.className='event-card';c.tabIndex=0;c.setAttribute('role','button');c.setAttribute('aria-label',`View ${ev[1]} gallery`);c.innerHTML=`<div class="event-icon">${ev[0]}</div><h3>${ev[1]}</h3><span>View gallery →</span>`;c.onclick=()=>openCategory(ev);c.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openCategory(ev)}};grid.appendChild(c)});
$('close').onclick=()=>$('modal').classList.remove('open');$('modal').onclick=e=>{if(e.target===$('modal'))$('modal').classList.remove('open')};document.addEventListener('keydown',e=>{if(e.key==='Escape')$('modal').classList.remove('open')});
loadMedia();setInterval(()=>loadMedia(true),90000);
